---
#
# User configuration
#
user:
  name: daniele
  full_name: "Daniele Pintore"
  primary_group: users
  additional_groups: wheel
  # /bin/bash or /bin/zsh
  shell: /bin/zsh
  # See country list by running `reflector --list-countries`
  country: "Italy,Germany,France"

git:
  name: "{{ user['full_name'] }}"
  # obfuscated a little so bots won't find it
  email_b64: "ZGFuaWVsZS5waW50b3JlMUBnbWFpbC5jb20K"
  defaultBranch: "main"
  defaultEditor: "nvim"
  # can be "cache", "store", "osxkeychain", or "manager"
  helper: "cache" # currently disabled
  # can be "true" or "false"
  rebase: "true" # currently disabled
  # see this https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt
  colorMoved: "zebra" # currently disabled

#
# Miscellaneous
#

# amd, intel, nvidia
gpu_drivers: nvidia

# if nvidia is selected apply nvidia tips and tricks from arch wiki
nvidia_tricks: true

# desktop environment to install
# "Hyprland"
desktop: hyprland

# only AMD or Intel CPUs are currently supported
# true or false
install_microcode: true

# whether to enable printing/scanning or not
# true or false
enable_printing: false # currently disabled

# whether to detect the scanner or not
# true or false
detect_scanner: false # currently disabled

# whether to enable bluetooth or not
# true or false
enable_bluetooth: true

# whether to install laptop tools
# true or false
laptop: false

# how many parallel downloads to run at once
pacman:
  parallel_downloads: 5

# set aur helper
# supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
aur_helper: yay

#
# Services
#

# if not using LVM, disable it
# true or false
disable_lvm: false # currently disabled

# if not using systemd homed, disable it
# true or false
disable_systemd_homed: false # currently disabled

#
# Packages
#
packages:
  - aardvark-dns
  - alsa-firmware
  - alsa-plugins
  - alsa-utils
  - android-file-transfer
  - base
  - base-devel
  - bitwarden
  - btrfs-progs
  - btrfs-progs
  - chromium
  - curl
  - debuginfod
  - discord
  - dnsmasq
  - dosfstools
  - efibootmgr
  - evince
  - f3d
  - ffmpeg
  - ffmpegthumbnailer
  - filezilla
  - firefox
  - flatpak
  - fzf
  - gdb
  - ghc
  - gimp
  - git
  - gnome-calculator
  - gnome-keyring
  - gnu-netcat
  - go
  - go-swagger
  - gvfs
  - gvfs-afc
  - gvfs-gphoto2
  - gvfs-smb
  - htop
  - hunspell-en_us
  - hunspell-it
  - ifuse
  - jadx
  - jdk-openjdk
  - jq
  - kid3
  - lib32-glibc
  - libgsf
  - libreoffice-fresh
  - libva-utils
  - libvirt
  - linux-firmware
  - linux-headers
  - loupe
  - lsof
  - man
  - man-db
  - man-pages
  - minicom
  - ncdu
  - neofetch
  - neovim
  - network-manager-applet
  - networkmanager
  - nm-connection-editor
  - nmap
  - npm
  - nwg-look
  - obs-studio
  - openscad
  - openssh
  - pamixer
  - pandoc-cli
  - patchelf
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - podman
  - podman-compose
  - polkit-kde-agent
  - pwndbg
  - pwninit
  - python-capstone
  - python-pip
  - python-psutil
  - python-ptrace
  - python-pycparser
  - python-pyelftools
  - python-pygments
  - python-pynvim
  - python-six
  - python-unicorn
  - qbittorrent
  - qemu-full
  - qpdf
  - radare2
  - rclone
  - ripgrep
  - ropper
  - rsync
  - slurp
  - sof-firmware
  - sqlitebrowser
  - steam
  - sudo
  - swaybg
  - telegram-desktop
  - texlive-basic
  - texlive-bin
  - texlive-fontsrecommended
  - texlive-latex
  - texlive-latexrecommended
  - thunderbird
  - tmux
  - udiskie
  - unrar
  - unzip
  - veracrypt
  - virt-manager
  - virtualbox
  - vlc
  - wev
  - wget
  - wireguard-tools
  - wireplumber
  - wireshark-qt
  - wl-clipboard
  - xwaylandvideobridge
  - zsh
  - zsh-syntax-highlighting

laptop_packages:
  - acpilight
  - fprintd

aur_packages:
  - android-apktool
  - anytype-bin
  - betaflight-configurator-bin
  - btrfs-assistant
  - burpsuite
  - cura-bin
  - dex2jar
  - dmg2img
  - google-chrome
  - httpie-desktop-bin
  - hyprpicker
  - jdownloader2
  - plymouth-theme-abstract-ring-alt-git
  - plymouth-theme-colorful-sliced-git
  - qdirstat
  - rofi-lbonn-wayland-git
  - teams-for-linux
  - termius
  - vdhcoapp-bin

laptop_aur_packages:
  - batsignal
  - pam-fprint-grosshack
  - tlpui

flatpaks:
  - com.github.tchx84.Flatseal
  - fr.handbrake.ghb
  - com.musixmatch.Musixmatch
  - com.usebottles.bottles
  - net.xm1math.Texmaker

base_fonts:
  - otf-font-awesome
  - ttf-agave-nerd
  - ttf-font-awesome


printing_scanning_packages:
  - cups
  - cups-pdf
  - sane
  - sane-airscan
  - simple-scan

printing_scanning_aur_packages:
  - brlaser-git
  - brscan4
