---
- name: Install desktop environment
  when: desktop == "hyprland"
  block:
    - name: Install Hyprland
      community.general.pacman:
        name:
          - sddm
          - hyprland
          - hyprpaper
          - hypridle
          - hyprlock
          - hyprcursor
          - waybar
          - dunst
          - inotify-tools
          - kitty
          - nemo
          - nemo-fileroller
          - nemo-image-converter
          - grim
          - xdg-desktop-portal-gtk
          - xdg-desktop-portal-hyprland
        state: present
      become: true

- name: Start systemd service - sddm.service
  ansible.builtin.systemd:
    name: sddm.service
    enabled: yes
  become: true

