---
- name: Install XWayland
  community.general.pacman:
    name:
      - xorg-xwayland
    state: present
  become: true

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: gpu_drivers

- name: Install GPU drivers (AMD)
  when: gpu_drivers == "amd"
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - xf86-video-amdgpu
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - mesa-vdpau
      - libva-mesa-driver
      # https://wiki.archlinux.org/title/Vulkan
      - vulkan-radeon
      # https://wiki.archlinux.org/title/GPGPU
      - rocm-hip-runtime
      - rocm-hip-sdk
      - hip-runtime-amd
      - rocm-core
      - rocm-opencl-runtime
      - rocm-opencl-sdk
    state: present
  become: true

- name: Install GPU drivers (Intel)
  when: gpu_drivers == "intel"
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - xf86-video-intel
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - intel-media-driver
      - libva-intel-driver
      # https://wiki.archlinux.org/title/Vulkan
      - vulkan-intel
      # https://wiki.archlinux.org/title/GPGPU
      - intel-compute-runtime
      - opencl-clover-mesa
    state: present
  become: true

- name: Install GPU drivers (Nvidia)
  when: gpu_drivers == "nvidia"
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      # https://wiki.archlinux.org/title/Xorg
      - nvidia-dkms
      # https://wiki.archlinux.org/title/Hardware_video_acceleration
      - nvidia-utils
      - lib32-nvidia-utils # for wine/steam
      # https://wiki.archlinux.org/title/GPGPU
      - cuda
      - opencl-nvidia
    state: present
  become: true

- name: Apply Nvidia tricks https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks
  when: gpu_drivers == "nvidia" and nvidia_tricks
  block:
    - name: Add nvidia kernel parameter
      ansible.builtin.lineinfile:
        create: true
        dest: "/etc/modprobe.d/nvidia.conf"
        line: "options nvidia NVreg_PreserveVideoMemoryAllocations=1"
      become: true
    - name: Start systemd service - nvidia-suspend.service
      ansible.builtin.systemd:
        name: nvidia-suspend.service
        enabled: yes
      become: true
    - name: Start systemd service - nvidia-resume.service
      ansible.builtin.systemd:
        name: nvidia-resume.service
        enabled: yes
      become: true
    - name: Start systemd service - nvidia-hibernate.service
      ansible.builtin.systemd:
        name: nvidia-hibernate.service
        enabled: yes
      become: true
